### PR TITLE
[WIP] Prepare for CI -- format the code and add lint

### PR DESCRIPTION
**Pull request by hao-fang**

### CODE REVIEW

**Comment by hao-fang** [comment]
Sorry I meant to create the PR on our ACL fork.

**Comment by srush** [comment]
I like these :) can we keep some of the core things (like formatting) in sync with the miniconf repo?

**Comment by hao-fang** [comment]
@srush sure. I'll break this PR into smaller ones so it's easier to review.
(My goal is to add a Github Action for CI eventually.)

**Comment by srush** [comment]
Don't spend too much time on it. I know you guys are busy. But the more we stay in sync early , the easier it will be for us to help you upstream

**Pull request closed without merging**
