### PR TITLE
Integrate SSO for chat and login

### PR DESCRIPTION
**Pull request by srush**
This PR is based on exploration into Chat on SSL and single sign on. 

* Used hosted sloppy.io as a cheap and scalable way for people to run their own rocket chat servers. 
* Include instructions for setting up the chat integration. 
* Created a demo page for login using Auth0. 
* Created a demo for using Auth0 for SSO into rocketchat. 

Here's what the signin screen looks like: 
Sign_In_with_Auth0

Here is the login screen for rocket chat. If there is an Auth0 account and they click "Miniconf" it signs in automatically. 
MiniConf_2020_Chat

### CODE REVIEW

**Comment by hao-fang** [comment]
@srush Sorry I might have missed something. When I run `make run` locally, I didn't see a login prompt. I can still browse all contents on the website.
Is this auth0 only works for RocketChat?

**Comment by srush** [comment]
So a couple things:

1) what url are you using for the base site? I set it up to only work for localhost:5000 .

2) if you are using a different rocket chat host you need to configure it internally.

Finally check that the console doesn't have other error messages.

It should redirect you automatically

**Comment by hao-fang** [comment]
Thanks! I was using `127.0.0.1:5000`. After I switch to `localhost:5000` it now redirects me to the auth0 login page 🎉 

But it is a little weird b/c it briefly shows the webpage before redirecting to the auth0 login page. Is this expected?

Also after I login using the `miniconf@miniconf.com` account, it shows this error page `https://miniconf.auth0.com/login/callback`
image
(But then I can visit `localhost:5000` without redirecting, which means the auth is successful.)
I guess you might need to configure the callback URL properly in the auth0 account.

**Comment by srush** [comment]
Ah I see, yes we need to give a "redirect_uri" arg. I will send a PR to have it go back to the default page. 

I will also see if we can have it redirect before showing any html.

**Comment by hao-fang** [comment]
Thanks!
I figured out a similar OAuth configuration using AWS Cognito for SSO so we may go with that solution for ACL.
But auth0 seems to be much easier to set up so it would be nice to make it work for future conferences. I just don't have a clear picture about how it would work for static website -- it seems to only work with a server, e.g., using Flask.

**Pull request merged**
